
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/register 

module register(Q, D, clk, reset, en);
  input [5:0] D;
  input clk, reset, en;
  output [5:0] Q;
  wire [5:0] D;
  wire clk, reset, en;
  wire [5:0] Q;
  wire n_0;
  DFCNQD1 \outreg_reg[5] (.CDN (n_0), .CP (clk), .D (D[5]), .Q (Q[5]));
  DFCNQD1 \outreg_reg[3] (.CDN (n_0), .CP (clk), .D (D[3]), .Q (Q[3]));
  DFCNQD1 \outreg_reg[0] (.CDN (n_0), .CP (clk), .D (D[0]), .Q (Q[0]));
  DFCNQD1 \outreg_reg[4] (.CDN (n_0), .CP (clk), .D (D[4]), .Q (Q[4]));
  DFCNQD1 \outreg_reg[2] (.CDN (n_0), .CP (clk), .D (D[2]), .Q (Q[2]));
  DFCNQD1 \outreg_reg[1] (.CDN (n_0), .CP (clk), .D (D[1]), .Q (Q[1]));
  CKND0 g11(.I (reset), .ZN (n_0));
endmodule

